modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/TheStaticVoid/CapeJS/issues"

[[mods]]
modId="capejs"
version="${version}"
displayName="CapeJS"
authors = "static"
logoFile="icon.png"
description='''
Mod utilizing KubeJS to add custom capes to players using scripts
'''
license = "MIT"

[[dependencies.capejs]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.capejs]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.capejs]]
modId = "kubejs"
mandatory = true
versionRange = "[2001.6.3-build.34,)"